import { Exam } from '../types/index.js';

export const SEED_COMMERCIAL_AND_GENERAL_EXAMS: Exam[] = [
  {
    id: 'exam_sss2_accounting',
    title: 'SSS 2 Financial Accounting - Double Entry & Ledgers',
    subject: 'Financial Accounting',
    session: '2024/2025',
    assessmentType: 'test',
    educationLevel: 'senior_secondary',
    targetClasses: ['SSS 2', 'SSS 3'],
    department: 'commercial',
    durationMinutes: 45,
    passingScore: 50,
    totalPoints: 20,
    teacherName: 'Mr. Bello',
    createdAt: new Date().toISOString(),
    isPublished: true,
    questions: [
      {
        id: 'q_acc_1',
        prompt: 'In double-entry bookkeeping, an increase in assets is recorded as a:',
        type: 'multiple_choice',
        options: ['Credit', 'Debit', 'Liability', 'Balance'],
        correctAnswer: 'Debit',
        points: 10,
        explanation: 'Debiting an asset account increases its balance.',
      },
      {
        id: 'q_acc_2',
        prompt: 'A trial balance is an account in the financial ledger.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        points: 10,
        explanation: 'A trial balance is a schedule to check arithmetic accuracy.',
      },
    ],
  },
  {
    id: 'exam_sss2_gen_math',
    title: 'SSS 2 General Mathematics - Term Examination',
    subject: 'General Mathematics',
    session: '2024/2025',
    assessmentType: 'exam',
    educationLevel: 'senior_secondary',
    targetClasses: ['SSS 2'],
    durationMinutes: 50,
    passingScore: 50,
    totalPoints: 20,
    teacherName: 'Mr. Danjuma',
    createdAt: new Date().toISOString(),
    isPublished: true,
    questions: [
      {
        id: 'q_gmath_1',
        prompt: 'Solve for x: 2^(x + 1) = 16',
        type: 'multiple_choice',
        options: ['2', '3', '4', '5'],
        correctAnswer: '3',
        points: 10,
        explanation: '16 = 2^4, so x + 1 = 4 -> x = 3.',
      },
      {
        id: 'q_gmath_2',
        prompt: 'The roots of x² - 5x + 6 = 0 are 2 and 3.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        points: 10,
        explanation: '(x - 2)(x - 3) = 0 gives x = 2 or x = 3.',
      },
    ],
  },
];
