import { Exam } from '../types/index.js';

export const SEED_SCIENCE_EXAMS: Exam[] = [
  {
    id: 'exam_sss2_physics',
    title: 'SSS 2 Physics - Mechanics & Wave Motion',
    subject: 'Physics',
    session: '2024/2025',
    assessmentType: 'exam',
    educationLevel: 'senior_secondary',
    targetClasses: ['SSS 2', 'SSS 3'],
    department: 'science',
    durationMinutes: 45,
    passingScore: 60,
    totalPoints: 40,
    teacherName: 'Dr. Mensah',
    createdAt: new Date().toISOString(),
    isPublished: true,
    questions: [
      {
        id: 'q_phy_1',
        prompt: 'What is the SI unit of momentum?',
        type: 'multiple_choice',
        options: ['kg m/s²', 'kg m/s', 'N/m', 'J/s'],
        correctAnswer: 'kg m/s',
        points: 10,
        explanation: 'Momentum is mass times velocity (kg * m/s).',
      },
      {
        id: 'q_phy_2',
        prompt: 'In projectile motion, horizontal velocity remains constant if air resistance is neglected.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        points: 10,
        explanation: 'No horizontal acceleration acts when air resistance is ignored.',
      },
      {
        id: 'q_phy_3',
        prompt: 'Which wave phenomenon is responsible for the spreading of waves around obstacles?',
        type: 'multiple_choice',
        options: ['Refraction', 'Diffraction', 'Polarization', 'Interference'],
        correctAnswer: 'Diffraction',
        points: 10,
        explanation: 'Diffraction is spreading around obstacles or slits.',
      },
      {
        id: 'q_phy_4',
        prompt: 'State the law of conservation of linear momentum.',
        type: 'short_answer',
        correctAnswer: 'The total momentum of an isolated system remains constant if no external force acts upon it.',
        points: 10,
        explanation: 'P_initial = P_final in a closed system.',
      },
    ],
  },
];
